# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 145328b9789dd7381477491a81ffd3a24056eee74709c7180932905054332f6b90a3499b2be886b3619254da9b8788e58dd6ba7c5ee5bd25891136133f603ad3

test:
  secret_key_base: 9a22d7bfb2dc7b2b880adc11183d9ddeb187c1c3d1338cd9e58c4745ed630201962322ddc92839493109fc3c0f3bd274ab2d52c40f99f91eadc8873557021eab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
